#!/usr/bin/env bash
sudo ifconfig lo0 alias 10.254.254.254
docker-sync start && \
docker-compose up -d && \
version=$(git describe --tags $(git rev-list --tags --max-count=1))
echo "
===================== 🚀 Done 🚀 ===================

      v.$version
      Access your new links:

      🌎 Web server (varnish): http://localhost/
      🌎 Web server : http://localhost:8000/
      ⚙️ PHPMyAdmin: http://localhost:8080
      ✉️ Local emails: http://localhost:8025

===================== 🚀 Done 🚀 ==================="
